version: "3.0"
services:
  bot:
    build: .
    volumes:
      - .:/code
    links:
      - db
  db:
    image: postgres:12-alpine
    volumes:
      - postgresdb:/var/lib/postgresql/data

volumes:
  postgresdb:
